export const FETCH_MOVIES_LISTS = 'FETCH_MOVIES_LISTS';
export const FETCH_SINGLE_MOVIE = 'FETCH_SINGLE_MOVIE';
export const STREAM_VIDEO = 'STREAM_VIDEO';
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
